<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>Dara.Server.BuildingBlocks.Infrastructure</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.8" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="10.0.8" />
        <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="10.0.3" />
    </ItemGroup>

    <ItemGroup>

      <ProjectReference Include="..\..\..\Shared\Logging\Dara.Shared.Logging.csproj" />

      <ProjectReference Include="..\Application\Dara.Server.BuildingBlocks.Application.csproj" />
      <ProjectReference Include="..\Domain\Dara.Server.BuildingBlocks.Domain.csproj" />
      <ProjectReference Include="..\Integration\Dara.Server.BuildingBlocks.Integration.csproj" />

        <ProjectReference Include="..\..\..\Shared\SourceGenerators\Dara.Shared.SourceGenerators.csproj"
                          OutputItemType="Analyzer"
                          ReferenceOutputAssembly="false" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" Version="10.0.8" />
    </ItemGroup>

    <ItemGroup>
      <Reference Include="Microsoft.Extensions.Hosting.Abstractions">
        <HintPath>..\..\..\..\..\..\..\.nuget\packages\microsoft.extensions.hosting.abstractions\10.0.8\lib\net10.0\Microsoft.Extensions.Hosting.Abstractions.dll</HintPath>
      </Reference>
    </ItemGroup>

</Project>
