<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\..\BuildingBlocks\Infrastructure\Dara.Server.BuildingBlocks.Infrastructure.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\Integration\Dara.Server.BuildingBlocks.Integration.csproj" />
    <ProjectReference Include="..\Application\Dara.Server.Modules.Groups.Application.csproj" />
    <ProjectReference Include="..\Domain\Dara.Server.Modules.Groups.Domain.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
